from .env_map import EnvMap



OPEN_MAP = EnvMap([
    "##########################################",
    "#            o      ooooo           o    #",
    "#        o   oo         ooo        o  o  #",
    "#     o ooo  ooo    o    o  o ooo oooo   #",
    "# o  ooo o    o  o ooo  o  ooo o   o o   #",
    "#ooo  o o    o  ooo o  ooo  o o       o  #",
    "# o o  ooo  ooo  o o    o o  ooo   oo oo #",
    "#  ooo  o    o o  ooo    ooo  o     ooo  #",
    "#   o         ooo  o      o          o   #",
    "#  ooo    o    o               o    ooo  #",
    "#   o  o ooo    o  o ooo      o  ooo o   #",
    "#  o  ooo o    o  ooo o      ooo  o o    #",
    "# ooo  o o    ooo  o o        o o  ooo   #",
    "#  o o  ooo    o o  ooo        ooo  o    #",
    "#   ooo  o      ooo  o    o  o ooo       #",
    "#    o       o  o ooo    o  ooo o        #",
    "#o  ooo  o  o  ooo o    ooo  o o         #",
    "#    o o   ooo  o o      o o  ooo        #",
    "#     ooo   o o  ooo      ooo  o         #",
    "# o    o     ooo  o        o             #",
    "#             o                          #",
    "##########################################",
], starting_zones=[((15, 34), (21, 41))])


SINGLE_ENTRANCE_MAP = EnvMap([
    "#######################################################",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "# ooo  ooo  ooo  ooo  ooo#   #ooo  ooo  ooo  ooo  ooo #",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "#                        #   #                        #",
    "#     o    o    o    o   #   #   o    o    o    o     #",
    "#    ooo  ooo  ooo  ooo# #   ###ooo  ooo  ooo  ooo    #",
    "#     o    o    o    o # #       o    o    o    o     #",
    "######################## #   ##########################",
    "#                                                     #",
    "#                                                     #",
    "#                                                     #",
    "##########################   # ########################",
    "#     o    o    o    o       # # o    o    o    o     #",
    "#    ooo  ooo  ooo  ooo###   # #ooo  ooo  ooo  ooo    #",
    "#     o    o    o    o   #   #   o    o    o    o     #",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "# ooo  ooo  ooo  ooo  ooo#   #ooo  ooo  ooo  ooo  ooo #",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "#######################################################",
], starting_zones=[((9, 1), (16, 24)), ((9, 31), (16, 54))])


MULTI_ENTRANCE_MAP = EnvMap([
    "#######################################################",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "# ooo  ooo  ooo  ooo  ooo    #ooo  ooo  ooo  ooo  ooo #",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "#                        #                            #",
    "#     o    o    o    o   #   #   o    o    o    o     #",
    "#    ooo  ooo  ooo  ooo# #   ###ooo  ooo  ooo  ooo    #",
    "#     o    o    o    o # #       o    o    o    o     #",
    "## ###### ############## #   ############ ####### #####",
    "#                                                     #",
    "#                                                     #",
    "#                                                     #",
    "##### ####### ############   # ############## ###### ##",
    "#     o    o    o    o   #   # # o    o    o    o     #",
    "#    ooo  ooo  ooo  ooo###   # #ooo  ooo  ooo  ooo    #",
    "#     o    o    o    o   #   #   o    o    o    o     #",
    "#  o    o    o    o    o     # o    o    o    o    o  #",
    "# ooo  ooo  ooo  ooo  ooo#    ooo  ooo  ooo  ooo  ooo #",
    "#  o    o    o    o    o #   # o    o    o    o    o  #",
    "#######################################################",
], starting_zones=[((9, 1), (16, 24)), ((9, 31), (16, 54))])